"""initial schema

Revision ID: 0001_initial_schema
Revises: 
Create Date: 2026-07-21 19:12:01.445790
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001_initial_schema'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('tier', sa.Enum('BRONZE', 'SILVER', 'GOLD', 'PLATINUM', name='achievementtier', native_enum=False, length=16), nullable=False),
    sa.Column('criteria_type', sa.Enum('WATCH_COUNT', 'UNIVERSE_COMPLETE', 'FRANCHISE_COMPLETE', 'GENRE_COUNT', 'RATING_COUNT', 'REWATCH_COUNT', 'COLLECTION_COMPLETE', name='achievementcriteriatype', native_enum=False, length=32), nullable=False),
    sa.Column('criteria_value', sa.Integer(), nullable=False),
    sa.Column('criteria_reference', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_achievements_key'), ['key'], unique=True)

    op.create_table('collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_image_path', sa.String(length=512), nullable=True),
    sa.Column('is_smart', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collections_slug'), ['slug'], unique=True)

    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('genres', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_genres_slug'), ['slug'], unique=True)

    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('photo_path', sa.String(length=512), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tmdb_id')
    )
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_people_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_people_slug'), ['slug'], unique=True)

    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('color_hex', sa.String(length=7), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tags_slug'), ['slug'], unique=True)

    op.create_table('universes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('abbreviation', sa.String(length=16), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color_hex', sa.String(length=7), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('universes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_universes_slug'), ['slug'], unique=True)

    op.create_table('franchises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('universe_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_path', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['universe_id'], ['universes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('franchises', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_franchises_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_franchises_universe_id'), ['universe_id'], unique=False)

    op.create_table('user_achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('progress_current', sa.Integer(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_achievements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_achievements_achievement_id'), ['achievement_id'], unique=True)

    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('project_type', sa.Enum('MOVIE', 'TV_SERIES', 'TV_SPECIAL', 'SHORT', 'DOCUMENTARY', 'ANIMATED_SERIES', name='projecttype', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('RELEASED', 'UPCOMING', 'ANNOUNCED', 'IN_PRODUCTION', 'CANCELLED', name='projectstatus', native_enum=False, length=32), nullable=False),
    sa.Column('universe_id', sa.Integer(), nullable=True),
    sa.Column('franchise_id', sa.Integer(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('runtime_minutes', sa.Integer(), nullable=True),
    sa.Column('studio', sa.String(length=128), nullable=True),
    sa.Column('synopsis', sa.Text(), nullable=True),
    sa.Column('poster_path', sa.String(length=512), nullable=True),
    sa.Column('background_path', sa.String(length=512), nullable=True),
    sa.Column('trailer_url', sa.String(length=512), nullable=True),
    sa.Column('saga', sa.String(length=128), nullable=True),
    sa.Column('phase', sa.String(length=64), nullable=True),
    sa.Column('chronological_order', sa.Integer(), nullable=True),
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.Column('imdb_id', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['franchise_id'], ['franchises.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['universe_id'], ['universes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('imdb_id'),
    sa.UniqueConstraint('tmdb_id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_chronological_order'), ['chronological_order'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_franchise_id'), ['franchise_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_release_date'), ['release_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_projects_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_universe_id'), ['universe_id'], unique=False)

    op.create_table('collection_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id', 'project_id', name='uq_collection_project')
    )
    with op.batch_alter_table('collection_projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collection_projects_collection_id'), ['collection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collection_projects_project_id'), ['project_id'], unique=False)

    op.create_table('project_cast',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('character_name', sa.String(length=160), nullable=True),
    sa.Column('billing_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'person_id', 'character_name', name='uq_cast_role')
    )
    with op.batch_alter_table('project_cast', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_cast_person_id'), ['person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_cast_project_id'), ['project_id'], unique=False)

    op.create_table('project_crew',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'person_id', 'role', name='uq_crew_role')
    )
    with op.batch_alter_table('project_crew', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_crew_person_id'), ['person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_crew_project_id'), ['project_id'], unique=False)

    op.create_table('project_genres',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'genre_id')
    )
    op.create_table('project_tags',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'tag_id')
    )
    op.create_table('user_project_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('watched', sa.Boolean(), nullable=False),
    sa.Column('favorite', sa.Boolean(), nullable=False),
    sa.Column('wishlist', sa.Boolean(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('last_watched_date', sa.Date(), nullable=True),
    sa.Column('rewatch_count', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_project_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_project_data_project_id'), ['project_id'], unique=True)

    op.create_table('watch_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('watched_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_rewatch', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('watch_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watch_history_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_watch_history_watched_at'), ['watched_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watch_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watch_history_watched_at'))
        batch_op.drop_index(batch_op.f('ix_watch_history_project_id'))

    op.drop_table('watch_history')
    with op.batch_alter_table('user_project_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_project_data_project_id'))

    op.drop_table('user_project_data')
    op.drop_table('project_tags')
    op.drop_table('project_genres')
    with op.batch_alter_table('project_crew', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_crew_project_id'))
        batch_op.drop_index(batch_op.f('ix_project_crew_person_id'))

    op.drop_table('project_crew')
    with op.batch_alter_table('project_cast', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_cast_project_id'))
        batch_op.drop_index(batch_op.f('ix_project_cast_person_id'))

    op.drop_table('project_cast')
    with op.batch_alter_table('collection_projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collection_projects_project_id'))
        batch_op.drop_index(batch_op.f('ix_collection_projects_collection_id'))

    op.drop_table('collection_projects')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_universe_id'))
        batch_op.drop_index(batch_op.f('ix_projects_title'))
        batch_op.drop_index(batch_op.f('ix_projects_slug'))
        batch_op.drop_index(batch_op.f('ix_projects_release_date'))
        batch_op.drop_index(batch_op.f('ix_projects_franchise_id'))
        batch_op.drop_index(batch_op.f('ix_projects_chronological_order'))

    op.drop_table('projects')
    with op.batch_alter_table('user_achievements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_achievements_achievement_id'))

    op.drop_table('user_achievements')
    with op.batch_alter_table('franchises', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_franchises_universe_id'))
        batch_op.drop_index(batch_op.f('ix_franchises_slug'))

    op.drop_table('franchises')
    with op.batch_alter_table('universes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_universes_slug'))

    op.drop_table('universes')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tags_slug'))

    op.drop_table('tags')
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_people_slug'))
        batch_op.drop_index(batch_op.f('ix_people_name'))

    op.drop_table('people')
    with op.batch_alter_table('genres', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_genres_slug'))

    op.drop_table('genres')
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collections_slug'))

    op.drop_table('collections')
    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_achievements_key'))

    op.drop_table('achievements')
    # ### end Alembic commands ###
